spring.application.name=mcsv-gateway
spring.config.import=optional:configserver:http://localhost:8888
jwt.secret=rapicancha-secret-key-debe-tener-al-menos-32-chars
resilience4j.circuitbreaker.instances.bookingCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.bookingCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.bookingCB.waitDurationInOpenState=10s