spring.application.name=mcsv-court
spring.config.import= optional:configserver:http://localhost:8888



server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/court_db
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka