server.port=8081

spring.application.name=mcsv-auth
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${DB_URL_AUTH}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka