server.port=8080

spring.application.name=mcsv-gateway

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Ruta para mcsv-auth
spring.cloud.gateway.routes[0].id=mcsv-auth
spring.cloud.gateway.routes[0].uri=lb://mcsv-auth
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**, /api/accounts/**, /api/profiles/**

# Ruta para mcsv-court
spring.cloud.gateway.routes[1].id=mcsv-court
spring.cloud.gateway.routes[1].uri=lb://mcsv-court
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/venues/**, /api/sport-courts/**, /api/venues-and-sport-court/**

# Ruta para mcsv-booking
spring.cloud.gateway.routes[2].id=mcsv-booking
spring.cloud.gateway.routes[2].uri=lb://mcsv-booking
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/bookings/**, /api/availability/**

eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/